name: PR must only change /data

on:
  pull_request:
    branches: [ main ]
    # (optional) restrict to data paths to run less often
    paths:
      - 'docs/data/**'
      - 'data/**'

permissions:
  contents: read
  pull-requests: read

jobs:
  check-data-paths:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Validate changed paths
        run: |
          base="${{ github.event.pull_request.base.sha }}"
          head="${{ github.event.pull_request.head.sha }}"
          CHANGED="$(git diff --name-only "$base" "$head")"
          echo "Changed files:"; echo "$CHANGED"

          # allow only under docs/data or data
          BAD="$(echo "$CHANGED" | grep -vE '^(docs/data/|data/)' || true)"
          if [ -n "$BAD" ]; then
            echo "❌ Disallowed changes detected:"; echo "$BAD"
            exit 1
          fi
          echo "✅ All changes are under allowed data directories."
